// frontend/src/components/AudioPlayer/index.tsx
/**
 * 音频播放器组件 - 支持 seg 切换与自动连播
 */
import React, { useState, useRef, useEffect } from 'react'
import { Button, Slider, Space, Tag } from 'antd'
import {
  CaretRightOutlined,
  PauseOutlined,
  StepBackwardOutlined,
  StepForwardOutlined,
} from '@ant-design/icons'
import { AudioSeg } from '../../types'

interface AudioPlayerProps {
  segs: AudioSeg[]
  currentSegIndex?: number
  onSegChange?: (index: number) => void
  highlightSegIndex?: number // 当前正在转写的 seg（高亮）
}

export default function AudioPlayer({
  segs,
  currentSegIndex: externalIndex,
  onSegChange,
  highlightSegIndex,
}: AudioPlayerProps) {
  const [currentIndex, setCurrentIndex] = useState(0)
  const [isPlaying, setIsPlaying] = useState(false)
  const [progress, setProgress] = useState(0)
  const audioRef = useRef<HTMLAudioElement>(null)

  const activeIndex = externalIndex ?? currentIndex
  const currentSeg = segs[activeIndex]

  useEffect(() => {
    if (audioRef.current && currentSeg) {
      audioRef.current.src = `/api/audio/file?path=${encodeURIComponent(currentSeg.file_path)}`
      audioRef.current.load()
      if (isPlaying) audioRef.current.play()
    }
  }, [activeIndex, currentSeg?.file_path])

  const handlePlayPause = () => {
    if (!audioRef.current) return
    if (isPlaying) {
      audioRef.current.pause()
    } else {
      audioRef.current.play()
    }
    setIsPlaying(!isPlaying)
  }

  const goToSeg = (index: number) => {
    if (index < 0 || index >= segs.length) return
    setCurrentIndex(index)
    onSegChange?.(index)
    setIsPlaying(true)
  }

  const handleEnded = () => {
    if (activeIndex < segs.length - 1) {
      goToSeg(activeIndex + 1)
    } else {
      setIsPlaying(false)
    }
  }

  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60)
    const s = Math.floor(seconds % 60)
    return `${m}:${s.toString().padStart(2, '0')}`
  }

  if (!segs.length) {
    return <div style={{ padding: 16, color: '#999' }}>无音频</div>
  }

  return (
    <div style={{ padding: 16, background: '#fafafa', borderRadius: 8, border: '1px solid #f0f0f0' }}>
      <audio
        ref={audioRef}
        onPlay={() => setIsPlaying(true)}
        onPause={() => setIsPlaying(false)}
        onEnded={handleEnded}
        onTimeUpdate={(e) => {
          const audio = e.currentTarget
          if (audio.duration) {
            setProgress((audio.currentTime / audio.duration) * 100)
          }
        }}
        style={{ display: 'none' }}
      />

      <div style={{ marginBottom: 12, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Space>
          <Tag color="blue">第 {activeIndex + 1} / {segs.length} 段</Tag>
          {currentSeg && <span style={{ color: '#666', fontSize: 12 }}>{currentSeg.filename}</span>}
        </Space>
        {highlightSegIndex !== undefined && highlightSegIndex !== activeIndex && (
          <Tag color="processing">正在转写第 {highlightSegIndex + 1} 段...</Tag>
        )}
      </div>

      <Slider value={progress} onChange={() => {}} tooltip={{ formatter: null }} />

      <div style={{ textAlign: 'center', marginTop: 8 }}>
        <Space size="large">
          <Button
            icon={<StepBackwardOutlined />}
            disabled={activeIndex === 0}
            onClick={() => goToSeg(activeIndex - 1)}
          />
          <Button
            type="primary"
            shape="circle"
            size="large"
            icon={isPlaying ? <PauseOutlined /> : <CaretRightOutlined />}
            onClick={handlePlayPause}
          />
          <Button
            icon={<StepForwardOutlined />}
            disabled={activeIndex === segs.length - 1}
            onClick={() => goToSeg(activeIndex + 1)}
          />
        </Space>
      </div>

      {/* seg 快捷列表 */}
      <div style={{ marginTop: 12, display: 'flex', gap: 4, flexWrap: 'wrap' }}>
        {segs.map((seg, idx) => (
          <Button
            key={seg.id}
            size="small"
            type={idx === activeIndex ? 'primary' : (idx === highlightSegIndex ? 'dashed' : 'default')}
            onClick={() => goToSeg(idx)}
          >
            {idx + 1}
          </Button>
        ))}
      </div>
    </div>
  )
}

// frontend/src/components/AudioPlayer/index.vue
<template>
  <div class="audio-player">
    <audio
      ref="audioRef"
      @play="isPlaying = true"
      @pause="isPlaying = false"
      @ended="onEnded"
      @timeupdate="onTimeUpdate"
      style="display: none"
    />

    <div v-if="segs.length === 0" style="padding: 16px; color: #999">无音频</div>

    <template v-else>
      <div class="info">
        <a-space>
          <a-tag color="blue">第 {{ activeIndex + 1 }} / {{ segs.length }} 段</a-tag>
          <span style="color: #666; font-size: 12px">{{ currentSeg?.filename }}</span>
        </a-space>
        <a-tag v-if="highlightSegIndex !== undefined && highlightSegIndex !== activeIndex" color="processing">
          正在转写第 {{ highlightSegIndex + 1 }} 段...
        </a-tag>
      </div>

      <a-slider v-model:value="progress" :tip-formatter="null" />

      <div class="controls">
        <a-space size="large">
          <a-button :disabled="activeIndex === 0" @click="goToSeg(activeIndex - 1)">
            <StepBackwardOutlined />
          </a-button>
          <a-button type="primary" shape="circle" size="large" @click="togglePlay">
            <PauseOutlined v-if="isPlaying" />
            <CaretRightOutlined v-else />
          </a-button>
          <a-button :disabled="activeIndex === segs.length - 1" @click="goToSeg(activeIndex + 1)">
            <StepForwardOutlined />
          </a-button>
        </a-space>
      </div>

      <div class="seg-list">
        <a-button
          v-for="(seg, idx) in segs"
          :key="seg.id"
          size="small"
          :type="idx === activeIndex ? 'primary' : (idx === highlightSegIndex ? 'dashed' : 'default')"
          @click="goToSeg(idx)"
        >
          {{ idx + 1 }}
        </a-button>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import type { AudioSeg } from '@/types'
import {
  CaretRightOutlined, PauseOutlined,
  StepBackwardOutlined, StepForwardOutlined,
} from '@ant-design/icons-vue'

const props = defineProps<{
  segs: AudioSeg[]
  currentSegIndex?: number
  highlightSegIndex?: number
}>()

const emit = defineEmits<{
  (e: 'segChange', index: number): void
}>()

const audioRef = ref<HTMLAudioElement | null>(null)
const activeIndex = ref(0)
const isPlaying = ref(false)
const progress = ref(0)
let userControlled = false

const currentSeg = computed(() => props.segs[activeIndex.value])

watch(() => props.currentSegIndex, (val) => {
  if (val !== undefined && !userControlled) {
    activeIndex.value = val
    userControlled = true
    loadAndPlay()
  }
})

watch(currentSeg, () => {
  loadAndPlay()
})

function loadAndPlay() {
  if (!audioRef.value || !currentSeg.value) return
  audioRef.value.src = `/api/audio/file?path=${encodeURIComponent(currentSeg.value.file_path)}`
  audioRef.value.load()
  if (isPlaying.value) audioRef.value.play()
}

function togglePlay() {
  if (!audioRef.value) return
  if (isPlaying.value) audioRef.value.pause()
  else audioRef.value.play()
}

function goToSeg(index: number) {
  if (index < 0 || index >= props.segs.length) return
  activeIndex.value = index
  emit('segChange', index)
  isPlaying.value = true
}

function onEnded() {
  if (activeIndex.value < props.segs.length - 1) {
    goToSeg(activeIndex.value + 1)
  } else {
    isPlaying.value = false
  }
}

function onTimeUpdate(e: Event) {
  const audio = e.currentTarget as HTMLAudioElement
  if (audio.duration) {
    progress.value = (audio.currentTime / audio.duration) * 100
  }
}

onMounted(() => {
  if (props.segs.length > 0) loadAndPlay()
})
</script>

<style scoped>
.audio-player { padding: 16px; background: #fafafa; border-radius: 8px; border: 1px solid #f0f0f0; }
.info { margin-bottom: 12px; display: flex; justify-content: space-between; align-items: center; }
.controls { text-align: center; margin-top: 8px; }
.seg-list { margin-top: 12px; display: flex; gap: 4px; flex-wrap: wrap; }
</style>
