// frontend/src/components/SegList/index.vue
<template>
  <div class="seg-list">
    <a-list :data-source="segs" size="small">
      <template #renderItem="{ item, index }">
        <a-list-item
          :style="{ cursor: 'pointer', background: index === currentSegIndex ? '#e6f4ff' : 'transparent', padding: '8px 12px' }"
          @click="emit('segClick', index)"
        >
          <a-list-item-meta>
            <template #avatar>
              <CheckCircleFilled v-if="getResult(item.seg_index)" style="color: #52c41a" />
              <LoadingOutlined v-else-if="index === currentSegIndex" style="color: #1677ff" />
              <WarningOutlined v-else style="color: #ccc" />
            </template>
            <template #title>
              <span style="font-size: 13px">
                <span style="font-weight: bold">第 {{ item.seg_index }} 段</span>
                <span style="margin-left: 8px; color: #666; font-size: 11px">{{ item.filename }}</span>
                <a-tag v-if="getResult(item.seg_index)" color="success" style="margin-left: 4px">已完成</a-tag>
                <a-tag v-else-if="index === currentSegIndex" color="processing" style="margin-left: 4px">转写中</a-tag>
                <a-tag v-else style="margin-left: 4px">未转写</a-tag>
              </span>
            </template>
            <template #description>
              <span v-if="getResult(item.seg_index)" style="font-size: 12px">{{ getResult(item.seg_index)!.text || '(空)' }}</span>
              <span v-else style="font-size: 12px; color: #999">等待转写...</span>
            </template>
          </a-list-item-meta>
        </a-list-item>
      </template>
    </a-list>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { AudioSeg, ASRSegResult } from '@/types'
import { CheckCircleFilled, LoadingOutlined, WarningOutlined } from '@ant-design/icons-vue'

const props = defineProps<{
  segs: AudioSeg[]
  asrResults: ASRSegResult[]
  currentSegIndex?: number
}>()

const emit = defineEmits<{
  (e: 'segClick', index: number): void
}>()

const resultMap = computed(() => {
  const map = new Map<number, ASRSegResult>()
  props.asrResults.forEach((r) => map.set(r.seg_index, r))
  return map
})

function getResult(segIndex: number): ASRSegResult | undefined {
  return resultMap.value.get(segIndex)
}
</script>

<style scoped>
.seg-list { max-height: 400px; overflow-y: auto; }
</style>

// frontend/src/components/SegList/index.tsx
/**
 * Seg 列表组件 - 显示每个 seg 的转写结果
 */
import React from 'react'
import { List, Tag, Typography } from 'antd'
import { CheckCircleFilled, LoadingOutlined, WarningOutlined } from '@ant-design/icons'
import { ASRSegResult, AudioSeg } from '../../types'

const { Text } = Typography

interface SegListProps {
  segs: AudioSeg[]
  asrResults: ASRSegResult[]
  currentSegIndex?: number
  onSegClick?: (index: number) => void
}

export default function SegList({ segs, asrResults, currentSegIndex, onSegClick }: SegListProps) {
  const resultMap = new Map(asrResults.map((r) => [r.seg_index, r]))

  return (
    <List
      size="small"
      dataSource={segs}
      renderItem={(seg, idx) => {
        const result = resultMap.get(seg.seg_index)
        const hasResult = !!result
        const isCurrent = idx === currentSegIndex

        let statusIcon = <WarningOutlined style={{ color: '#ccc' }} />
        let statusTag = <Tag>未转写</Tag>
        if (hasResult) {
          statusIcon = <CheckCircleFilled style={{ color: '#52c41a' }} />
          statusTag = <Tag color="success">已完成</Tag>
        } else if (idx === currentSegIndex) {
          statusIcon = <LoadingOutlined style={{ color: '#1677ff' }} />
          statusTag = <Tag color="processing">转写中</Tag>
        }

        return (
          <List.Item
            key={seg.id}
            style={{
              cursor: 'pointer',
              background: isCurrent ? '#e6f4ff' : 'transparent',
              padding: '8px 12px',
              borderRadius: 4,
            }}
            onClick={() => onSegClick?.(idx)}
          >
            <List.Item.Meta
              avatar={statusIcon}
              title={
                <span style={{ fontSize: 13 }}>
                  <Text strong>第 {seg.seg_index} 段</Text>
                  <Text type="secondary" style={{ marginLeft: 8, fontSize: 11 }}>
                    {seg.filename}
                  </Text>
                  {statusTag}
                </span>
              }
              description={
                hasResult ? (
                  <Text style={{ fontSize: 12 }}>{result!.text || '(空)'}</Text>
                ) : (
                  <Text type="secondary" style={{ fontSize: 12 }}>等待转写...</Text>
                )
              }
            />
          </List.Item>
        )
      }}
    />
  )
}
